# Generated by Django 6.0.7 on 2026-07-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='fecha_contratacion',
            field=models.DateField(verbose_name='Fecha de contratacion'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
    ]
