# Generated by Django 6.0.7 on 2026-07-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Estatura (m)')),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de grasa')),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa muscular (kg)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadores.entrenador', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Evaluación física',
                'verbose_name_plural': 'Evaluaciones físicas',
                'ordering': ['-fecha'],
            },
        ),
    ]
