# Generated by Django 6.0.7 on 2026-07-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
        ('clientes', '0002_alter_cliente_apellido_materno_alter_cliente_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
